/*HTML5 Video Player with Bottom Playlist v4.7.3*/
(function(e) { e.fn.vp2_html5_bottomPlaylist_Video = function(t) { var i, s, o, n, d, r, h, l, c, a, u, m, p, g, f, w, b, v = !1,
            x = !1;
        t = e.extend({ skin: "universalBlack", initialVolume: 1, showInfo: 0, autoPlayFirstMovie: 0, autoPlay: 0, loop: 1, autoHideControllers: 0, seekBarAdjust: 255, borderWidth: 0, borderColor: "#000", numberOfThumbsPerScreen: 6, thumbsReflection: 0, isSliderInitialized: !1, isProgressInitialized: !1, responsive: 1, responsiveRelativeToBrowser: 1, width: 0, height: 0, width100Proc: !1, height100Proc: !1, showPlaylistOnInit: !0, showPlaylistBut: !0, autoPlayOnMobile: !1, setOrigWidthHeight: !0, thumbsOnMarginTop: 10, origWidth: 0, origHeight: 0, origThumbW: 0, origThumbH: 0, origthumbsHolderWrapperH: 121, origthumbsHolder_MarginTop: 0, windowOrientationScreenSize0: 0, windowOrientationScreenSize90: 0, windowOrientationScreenSize_90: 0, windowCurOrientation: 0 }, t); var y = function() { var e = -1; if ("Microsoft Internet Explorer" == navigator.appName) { var t = navigator.userAgent,
                    i = /MSIE ([0-9]{1,}[.0-9]{0,})/;
                null != i.exec(t) && (e = parseFloat(RegExp.$1)) } else "Netscape" == navigator.appName && (t = navigator.userAgent, i = /Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/, null != i.exec(t) && (e = parseFloat(RegExp.$1))); return parseInt(e, 10) }(); return this.each(function() {
            function O() { if (document.getElementById(i).readyState) { w = document.getElementById(i).duration, z.slider({ value: 0, step: .01, orientation: "horizontal", range: "min", max: w, animate: !0, slide: function() { pe = !0 }, stop: function(e, t) { pe = !1, document.getElementById(i).currentTime = t.value }, create: function(e, i) { t.isSliderInitialized = !0 } }); var e = 0;
                    M.progressbar({ value: e, create: function(e, i) { t.isProgressInitialized = !0 } }), I.bind("progress", function() { e = document.getElementById(i).buffered.end(document.getElementById(i).buffered.length - 1), 0 < e && M.progressbar({ value: e * M.css("width").substring(0, M.css("width").length - 2) / w }) }), C.show() } else setTimeout(O, 200) } var I = e(this);
            i = I.attr("id"); var W = 0,
                T = 0,
                H = 0,
                P = 150,
                B = 0,
                C = e('<div class="VideoControls"><a class="VideoRewind" title="Rewind"></a><a class="VideoPlay" title="Play/Pause"></a><div class="VideoBuffer"></div><div class="VideoSeek"></div><a class="VideoShowHidePlaylist" title="Show/Hide Playlist"></a><a class="VideoInfoBut" title="Info"></a><div class="VideoTimer">00:00</div><div class="VolumeAll"><div class="VolumeSlider"></div><a class="VolumeButton" title="Mute/Unmute"></a></div><a class="VideoFullScreen" title="FullScreen"></a></div> <div class="VideoInfoBox"></div>    <div class="thumbsHolderWrapper"><div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div>    </div>'),
                E = I.parent(".vp2_html5_bottomPlaylist"),
                _ = E.parent(".vp2_html5_bottomPlaylistBorder");
            E.addClass(t.skin), E.append(C), C = e(".VideoControls", E); var V = e(".VideoInfoBox", E),
                S = e(".VideoRewind", E),
                k = e(".VideoPlay", E),
                M = e(".VideoBuffer", E),
                z = e(".VideoSeek", E),
                N = e(".VideoInfoBut", E),
                R = e(".VideoShowHidePlaylist", E); if (!t.showInfo) { N.addClass("hideElement"), B += 14; var A = R.css("right").substr(0, R.css("right").lastIndexOf("px"));
                R.css({ right: A - 18 + "px" }) }
            t.showPlaylistBut || (R.addClass("hideElement"), B += 25); var F = e(".VideoTimer", E),
                D = e(".VolumeAll", E),
                L = e(".VolumeSlider", E),
                j = e(".VolumeButton", E),
                Z = e(".VideoFullScreen", E),
                $ = e(".thumbsHolderWrapper", E),
                Q = e(".thumbsHolderVisibleWrapper", E),
                U = e(".thumbsHolder", E),
                q = e('<div class="carouselLeftNav"></div>'),
                G = e('<div class="carouselRightNav"></div>');
            $.append(q), $.append(G), G.css("left", $.width() - G.width() + "px"), U.css("width", q.width() + "px"), C.width(I.width()), _.width(I.width() + 2 * t.borderWidth), _.height(I.height() + 3 * t.borderWidth + $.height()), _.css("background", t.borderColor), E.css({ width: I.width() + "px", height: I.height() + "px", top: t.borderWidth + "px", left: t.borderWidth + "px" }); var J = navigator.userAgent.toLowerCase();!t.autoPlayOnMobile || -1 == J.indexOf("ipad") && -1 == J.indexOf("iphone") && -1 == J.indexOf("ipod") && -1 == J.indexOf("webos") && -1 == navigator.userAgent.indexOf("Android") || (document.getElementById(i).muted = !0, document.getElementById(i).setAttribute("playsinline", "playsinline")), z.css("width", I[0].offsetWidth - t.seekBarAdjust + B + "px"), M.css("width", z.css("width")), V.css("width", I[0].offsetWidth - 40 + "px"), C.hide(), t.origWidth = document.getElementById(i).offsetWidth, t.origHeight = document.getElementById(i).offsetHeight, t.width = t.origWidth, t.height = t.origHeight, d = I.css("position"), r = I.css("left"), h = I.css("top"), l = E[0].offsetWidth, c = E[0].offsetHeight, a = E.css("position"), u = E.css("left"), m = E.css("top"), g = V.css("position"), p = C.css("position"), $.css("width", t.origWidth + "px"), o = _.css("position"), n = _.css("z-index"), videoContainerOrigZIndex = E.css("z-index"), videoControllersOrigBottom = C.css("bottom"), g = V.css("position"), t.responsive && (t.width100Proc || t.height100Proc) && (t.setOrigWidthHeight = !1), s = e("html").css("overflow"), C.css("width", "100%"); var K, X = function() { return document.getElementById(i).canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"') },
                Y = function() { e(he[ie]).addClass("thumbsHolder_ThumbON"), de(); var t = oe[ie].sources_webm,
                        i = navigator.userAgent.toLowerCase(); return -1 == i.indexOf("chrome") && -1 == i.indexOf("msie") && -1 == i.indexOf("safari") && -1 == i.indexOf("android") || (t = oe[ie].sources_mp4), -1 == i.indexOf("ipad") && -1 == i.indexOf("iphone") && -1 == i.indexOf("ipod") && -1 == i.indexOf("webos") || (t = oe[ie].sources_mp4), -1 != i.indexOf("android") && (t = oe[ie].sources_mp4), -1 != y && (t = oe[ie].sources_mp4), -1 != i.indexOf("opera") && (t = oe[ie].sources_webm, "" != X() && (t = oe[ie].sources_mp4)), -1 != i.indexOf("opr/") && (t = oe[ie].sources_webm, "" != X() && (t = oe[ie].sources_mp4)), -1 == i.indexOf("firefox") && -1 == i.indexOf("mozzila") || (t = oe[ie].sources_webm, "" != X() && (t = oe[ie].sources_mp4)), t },
                ee = !1,
                te = 0,
                ie = 0,
                se = 0,
                oe = [];
            e(".xplaylist", I).children().each(function() { currentElement = e(this), se++, oe[se - 1] = [], oe[se - 1].title = "", oe[se - 1].desc = "", oe[se - 1].thumb = "", oe[se - 1].preview = "", oe[se - 1].xsources_mp4 = "", oe[se - 1].xsources_ogv = "", oe[se - 1].xsources_webm = "", oe[se - 1].xsources_mp4v = "", null != currentElement.find(".xtitle").html() && (oe[se - 1].title = currentElement.find(".xtitle").html()), null != currentElement.find(".xdesc").html() && (oe[se - 1].desc = currentElement.find(".xdesc").html()), null != currentElement.find(".xthumb").html() && (oe[se - 1].thumb = currentElement.find(".xthumb").html()), null != currentElement.find(".xpreview").html() && (oe[se - 1].preview = currentElement.find(".xpreview").html()), null != currentElement.find(".xsources_mp4").html() && (oe[se - 1].sources_mp4 = currentElement.find(".xsources_mp4").html()), null != currentElement.find(".xsources_ogv").html() && (oe[se - 1].sources_ogv = currentElement.find(".xsources_ogv").html()), null != currentElement.find(".xsources_webm").html() && (oe[se - 1].sources_webm = currentElement.find(".xsources_webm").html()), null != currentElement.find(".xsources_mp4v").html() && (oe[se - 1].sources_mp4v = currentElement.find(".xsources_mp4v").html()), K = e('<div class="thumbsHolder_ThumbOFF" rel="' + (se - 1) + '"><img src="' + oe[se - 1].thumb + '"></div>'), U.append(K), 0 == t.numberOfThumbsPerScreen && (t.numberOfThumbsPerScreen = Math.floor((t.origWidth - q.width() - G.width()) / K.width())), H = Math.floor(($.width() - q.width() - G.width() - K.width() * t.numberOfThumbsPerScreen) / (t.numberOfThumbsPerScreen - 1)), U.css("width", U.width() + H + K.width() + "px"), 1 >= se ? K.css("margin-left", Math.floor(($.width() - q.width() - G.width() - (H + K.width()) * (t.numberOfThumbsPerScreen - 1) - K.width()) / 2) + "px") : K.css("margin-left", H + "px"), t.origThumbW = K.width(), t.origThumbH = K.height(), t.origthumbsHolderWrapperH = $.height(), thumbsHolder_MarginTop = parseInt(($.height() - parseInt(K.css("height").substring(0, K.css("height").length - 2))) / 2) }), Q.css("width", Q.width() - q.width() - G.width()), Q.css("left", q.width()), T = (K.width() + H) * t.numberOfThumbsPerScreen, 0 === Math.floor(ie / t.numberOfThumbsPerScreen) && q.addClass("carouselLeftNavDisabled"), Math.floor(ie / t.numberOfThumbsPerScreen) == Math.floor(se / t.numberOfThumbsPerScreen) && G.addClass("carouselRightNavDisabled"), $.css("top", I[0].offsetHeight + t.borderWidth + "px"), 0 < t.thumbsReflection && (thumbsHolder_MarginTop -= 7), A = e(".thumbsHolder_ThumbOFF", E).find("img:first"), A.css("margin-top", thumbsHolder_MarginTop + "px"); var ne = { opacity: t.thumbsReflection / 100 };
            0 < t.thumbsReflection && A.reflect(ne), K.css("background-position", "center " + t.thumbsOnMarginTop + "px"), q.click(function() { ee || (te = U.css("left").substr(0, U.css("left").lastIndexOf("px")), 0 > te && de(1)) }), G.click(function() { ee || (te = U.css("left").substr(0, U.css("left").lastIndexOf("px")), Math.abs(te - T) < (K.width() + H) * se && de(-1)) }); var de = function(e) { te = U.css("left").substr(0, U.css("left").lastIndexOf("px")), 1 === e || -1 === e ? (ee = !0, U.css("opacity", "0.5"), U.animate({ opacity: 1, left: "+=" + e * T }, 500, "easeOutCubic", function() { re(), ee = !1 })) : te != -1 * Math.floor(ie / t.numberOfThumbsPerScreen) * T && (ee = !0, U.css("opacity", "0.5"), U.animate({ opacity: 1, left: -1 * Math.floor(ie / t.numberOfThumbsPerScreen) * T }, 500, "easeOutCubic", function() { re(), ee = !1 })) },
                re = function() { te = U.css("left").substr(0, U.css("left").lastIndexOf("px")), 0 > te ? q.hasClass("carouselLeftNavDisabled") && q.removeClass("carouselLeftNavDisabled") : q.addClass("carouselLeftNavDisabled"), Math.abs(te - T) < (K.width() + H) * se ? G.hasClass("carouselRightNavDisabled") && G.removeClass("carouselRightNavDisabled") : G.addClass("carouselRightNavDisabled") },
                he = e(".thumbsHolder_ThumbOFF", E);
            he.click(function() { var i = e(this).attr("rel");
                ie != i && (e(he[ie]).removeClass("thumbsHolder_ThumbON"), ie = i, le(t.autoPlay)) }), he.mouseenter(function() { var t = e(this);
                t.attr("rel"), t.addClass("thumbsHolder_ThumbON") }), he.mouseleave(function() { var t = e(this),
                    i = t.attr("rel");
                ie != i && t.removeClass("thumbsHolder_ThumbON") }), he.dblclick(function(t) { t = e(this), t.attr("rel"), t.addClass("thumbsHolder_ThumbON") }); var le = function(e) { t.isSliderInitialized && (z.slider("destroy"), t.isSliderInitialized = !1), t.isProgressInitialized && (M.progressbar("destroy"), I.unbind("progress"), t.isProgressInitialized = !1), b = "Infinity", document.getElementById(i).poster = oe[ie].preview, V.html('<p class="movieTitle">' + oe[ie].title + '</p><p class="movieDesc">' + oe[ie].desc + "</p>"), document.getElementById(i).src = Y(), document.getElementById(i).load(); var s = navigator.userAgent.toLowerCase(); - 1 != s.indexOf("ipad") || -1 != s.indexOf("iphone") || -1 != s.indexOf("ipod") || -1 != s.indexOf("webos") || -1 != s.indexOf("android") ? (e ? (document.getElementById(i).play(), k.addClass("VideoPause")) : k.removeClass("VideoPause"), O()) : (clearInterval(b), b = setInterval(function() { 0 < document.getElementById(i).readyState && !isNaN(document.getElementById(i).duration) && "Infinity" != document.getElementById(i).duration && (w = document.getElementById(i).duration, O(), e ? (document.getElementById(i).play(), k.addClass("VideoPause")) : k.removeClass("VideoPause"), clearInterval(b)) }, 700)) };
            le(t.autoPlayFirstMovie), S.click(function() { document.getElementById(i).currentTime = 0, document.getElementById(i).play() }); var ce = function() { 0 == document.getElementById(i).paused ? document.getElementById(i).pause() : document.getElementById(i).play() };
            k.click(ce), I.click(ce), I.bind("play", function() { k.addClass("VideoPause") }), I.bind("pause", function() { k.removeClass("VideoPause") }), -1 == J.indexOf("ipad") && -1 == J.indexOf("iphone") && -1 == J.indexOf("ipod") && -1 == J.indexOf("webos") && (E.mouseover(function() { t.autoHideControllers && C.show() }), E.mouseout(function() { t.autoHideControllers && 120 > D.css("height").substring(0, D.css("height").length - 2) && C.hide() })), E.keydown(function(e) { 32 == e.keyCode && ce() }); var ae = function() { if (v = !0, Z.removeClass("VideoFullScreen"), Z.addClass("VideoFullScreenIn"), e("html").css("overflow", "hidden"), e("body").css("margin", 0), e(".vp2_html5_bottomPlaylist").css("display", "none"), E.css("display", "block"), "none" != $.css("display")) var i = window.innerHeight - $.height(),
                        s = window.innerHeight - i + "px";
                    else i = window.innerHeight, s = videoControllersOrigBottom;
                    I.css("position", "fixed"), I.css("width", window.innerWidth + "px"), I.css("height", i + "px"), I.css("top", 0), I.css("left", 0), E.css("position", "fixed"), E.css("width", "100%"), E.css("height", "20000px"), E.css("top", 0), E.css("left", 0), E.css("z-index", 1e4), C.css("position", "fixed"), C.css("bottom", s), z.css("width", window.innerWidth - t.seekBarAdjust + B + "px"), M.css("width", z.css("width")), V.css("position", "fixed"), V.css("width", window.innerWidth - 40 + "px"), "none" != $.css("display") && V.css("margin-bottom", $.height() + "px"), $.css("top", window.innerHeight - $.height() + "px"), $.css("margin-left", Math.round((window.innerWidth - t.origWidth) / 2)) },
                ue = function() { v = !1, Z.removeClass("VideoFullScreenIn"), Z.addClass("VideoFullScreen"), e("body").css("margin", void 0), e("html").css("overflow", s), e(".vp2_html5_bottomPlaylist").css("display", "block"), _.css("position", o), _.css("width", t.origWidth + 2 * t.borderWidth + "px"), _.css("height", t.origHeight + 3 * t.borderWidth + $.height() + "px"), _.css("background", t.borderColor), _.css("z-index", n), E.css("position", a), E.css("width", l + "px"), E.css("height", c + "px"), E.css("top", m), E.css("left", u), E.css("z-index", videoContainerOrigZIndex), E.css("top", m), E.css("left", u), C.css("position", p), C.css({ bottom: 0, "margin-bottom": 0 }), z.css("width", t.origWidth - t.seekBarAdjust + B + "px"), M.css("width", z.css("width")), V.css("width", t.origWidth - 40 + "px"), V.css("position", g), V.css("margin-bottom", "0px"), I.css("position", d), I.css("width", t.origWidth + "px"); var i = "none" != $.css("display") ? t.origHeight : t.origHeight + $.height() + t.borderWidth;
                    I.css("height", i + "px"), E.css("height", i + "px"), I.css("top", h), I.css("left", r), $.css("margin-left", 0), $.css("top", I[0].offsetHeight + t.borderWidth + "px") };
            E.dblclick(function() { v || Z.click() }), Z.click(function() { screenfull.enabled ? (E.css("display", "none"), screenfull.toggle(_[0]), screenfull.onchange = function(e) { t.responsive && t.width != t.origWidth && !v && (t.width = t.origWidth, t.height = t.origHeight, I.css("width", t.width + "px"), I.css("height", t.height + "px"), E.css("width", t.width + "px"), E.css("height", t.height + "px"), C.css("bottom", videoControllersOrigBottom), z.css("width", t.width - t.seekBarAdjust + B + "px"), M.css("width", z.css("width")), V.css("width", t.width - 40 + "px"), we()), delayTime = 50, 11 <= y && (delayTime = 200), setTimeout(function() { v ? ue() : ae() }, delayTime) }) : (-1 != y || -1 != J.indexOf("ipad") || -1 != J.indexOf("iphone") || -1 != J.indexOf("ipod") || -1 != J.indexOf("webos")) && t.responsive && t.responsiveRelativeToBrowser && t.width100Proc && t.height100Proc || (v ? ue() : ae()) }); var me = !1;
            F.mouseover(function() { me = !0, f = document.getElementById(i).currentTime, w = document.getElementById(i).duration, F.text("-" + ge(w - f)) }), F.mouseout(function() { me = !1, f = document.getElementById(i).currentTime, w = document.getElementById(i).duration, F.text(ge(f)) }); var pe = !1;
            O(); var ge = function(e) { var t = 10 > Math.floor(e / 60) ? "0" + Math.floor(e / 60) : Math.floor(e / 60); return t + ":" + (10 > Math.floor(e - 60 * t) ? "0" + Math.floor(e - 60 * t) : Math.floor(e - 60 * t)) };
            I.bind("timeupdate", function() { t.isSliderInitialized && (f = document.getElementById(i).currentTime, w = document.getElementById(i).duration, pe || z.slider("value", f), me ? F.text("-" + ge(w - f)) : F.text(ge(f))) }), N.click(function() { "giant" == t.skin ? "none" == V.css("display") ? V.fadeIn() : V.fadeOut() : V.slideToggle(300) }), R.click(function() { if (!x)
                    if (x = !0, "none" != $.css("display")) { var e = I[0].offsetHeight + t.borderWidth + $.height();
                        R.addClass("VideoShowHidePlaylist_onlyShow"), v ? (C.css({ bottom: 0, "margin-bottom": 0 }), V.css("margin-bottom", 0)) : E.css("height", e + "px"), $.animate({ opacity: 0 }, P, function() { $.css("display", "none") }), I.animate({ height: e }, 300, function() { x = !1 }) } else e = I[0].offsetHeight - t.borderWidth - $.height(), R.removeClass("VideoShowHidePlaylist_onlyShow"), v ? (C.css("margin-bottom", $.height() + "px"), V.css("margin-bottom", $.height() + "px")) : E.css("height", t.height + "px"), $.css("display", "block"), $.css("top", e + t.borderWidth + "px"), $.animate({ opacity: 1 }, 600, function() { x = !1, de() }), I.animate({ height: e }, 300, function() {}) }), t.showPlaylistOnInit || (P = 0, R.click(), P = 150), I[0].addEventListener("ended", function(i) { t.loop && -1 == J.indexOf("android") && (e(he[ie]).removeClass("thumbsHolder_ThumbON"), ie == se - 1 ? ie = 0 : ie++, le(t.autoPlay)) }, !1); var fe = 1;
            L.slider({ value: t.initialVolume, orientation: "vertical", range: "min", max: 1, step: .05, animate: !0, slide: function(e, t) { document.getElementById(i).muted = !1, fe = t.value, document.getElementById(i).volume = t.value } }), document.getElementById(i).volume = t.initialVolume, j.click(function() { 1 == document.getElementById(i).muted ? (document.getElementById(i).muted = !1, L.slider("value", fe), j.removeClass("VolumeButtonMute"), j.addClass("VolumeButton")) : (document.getElementById(i).muted = !0, L.slider("value", "0"), j.removeClass("VolumeButton"), j.addClass("VolumeButtonMute")) }), I.removeAttr("controls"); var we = function() { $.css({ top: I[0].offsetHeight + t.borderWidth + "px", width: t.width + "px", height: parseInt(t.origthumbsHolderWrapperH / (t.origWidth / t.width), 10) + "px" }), thumbIconCorrection = -7, bgTopCorrection = 0, 1 == t.origWidth / t.width && 0 < t.thumbsReflection && (bgTopCorrection = -7, thumbIconCorrection = 0), q.css("background-position", "0px " + (($.height() - t.origthumbsHolderWrapperH) / 2 + bgTopCorrection + 3) + "px"), G.css("background-position", "0px " + (($.height() - t.origthumbsHolderWrapperH) / 2 + bgTopCorrection + 3) + "px"), G.css("left", $.width() - G.width() + "px"), Q.css("width", t.width - q.width() - G.width()), t.origWidthThumbsHolderVisibleWrapper = t.origWidth - q.width() - G.width(), he.css({ width: parseInt(t.origThumbW / (t.origWidthThumbsHolderVisibleWrapper / Q.width()), 10) + "px", height: parseInt(t.origThumbH / (t.origWidthThumbsHolderVisibleWrapper / Q.width()), 10) + "px" }), t.numberOfThumbsPerScreen >= se && Q.css("left", parseInt(($.width() - (K.width() + H) * se) / 2, 10) + parseInt(H / 2, 10) + "px"); var i = e(".thumbsHolder_ThumbOFF", E).find("img:first");
                0 < t.thumbsReflection && i.unreflect(), i.css({ width: he.width() + "px", height: he.height() + "px", "margin-top": parseInt(($.height() - he.height()) / 2, 10) + bgTopCorrection + "px" }), 1 == t.origWidth / t.width && 0 < t.thumbsReflection && i.reflect({ opacity: t.thumbsReflection / 100 }), H = Math.floor(($.width() - q.width() - G.width() - K.width() * t.numberOfThumbsPerScreen) / (t.numberOfThumbsPerScreen - 1)), thumb_i = -1, U.children().each(function() { thumb_i++, theThumb = e(this), theThumb.css("background-position", "center " + parseInt((t.thumbsOnMarginTop - thumbIconCorrection) / (t.origWidth / t.width), 10) + "px"), 0 >= thumb_i ? theThumb.css("margin-left", Math.floor(($.width() - q.width() - G.width() - (H + theThumb.width()) * (t.numberOfThumbsPerScreen - 1) - theThumb.width()) / 2) + "px") : theThumb.css("margin-left", H + "px") }), T = (K.width() + H) * t.numberOfThumbsPerScreen };
            we(); var be = function() { if (v) - 1 == J.indexOf("ipad") && -1 == J.indexOf("iphone") && -1 == J.indexOf("ipod") && -1 == J.indexOf("webos") || Z.click();
                    else if (responsiveWidth = _.parent().width(), responsiveHeight = _.parent().height(), t.responsiveRelativeToBrowser && (responsiveWidth = e(window).width(), responsiveHeight = e(window).height()), t.width100Proc && (t.width = responsiveWidth - 1), t.height100Proc && (t.height = responsiveHeight), t.origWidth != responsiveWidth || t.width100Proc) { t.origWidth > responsiveWidth || t.width100Proc ? t.width = responsiveWidth : t.width100Proc || (t.width = t.origWidth), t.height100Proc || (t.height = t.width * t.origHeight / t.origWidth), t.width = responsiveWidth > t.width ? parseInt(t.width, 10) : parseInt(t.width, 10) - 2 * t.borderWidth, t.height = parseInt(t.height, 10); var i = t.height; "none" == $.css("display") && (i = t.height + t.borderWidth + $.height()), I.css("width", t.width + "px"), I.css("height", i + "px"), E.css("width", t.width + "px"), E.css("height", i + "px"), C.css("bottom", videoControllersOrigBottom), z.css("width", t.width - t.seekBarAdjust + B + "px"), M.css("width", z.css("width")), V.css("width", t.width - 40 + "px"), t.setOrigWidthHeight || (t.origWidth = t.width, t.origHeight = t.height, l = E[0].offsetWidth, c = E[0].offsetHeight), we(), de(), _.width(I.width() + 2 * t.borderWidth), "none" != $.css("display") ? _.height(I.height() + 3 * t.borderWidth + $.height()) : _.height(i + 2 * t.borderWidth) } },
                ve = !1;
            e(window).resize(function() { doResizeNow = !0, -1 != y && 9 == y && 0 == W && (doResizeNow = !1), W == e(window).width() ? (doResizeNow = !1, t.windowCurOrientation != window.orientation && -1 != navigator.userAgent.indexOf("Android") && (t.windowCurOrientation = window.orientation, doResizeNow = !0)) : W = e(window).width(), t.responsive && doResizeNow && (!1 !== ve && clearTimeout(ve), ve = setTimeout(function() { be() }, 300)) }), t.responsive && be() }) }, e.fn.vp2_html5_bottomPlaylist_Video.skins = {} })(jQuery);
/*screenfull*/
! function() { "use strict"; var a = "undefined" != typeof module && module.exports,
        b = "undefined" != typeof Element && "ALLOW_KEYBOARD_INPUT" in Element,
        c = function() { for (var a, b, c = [
                    ["requestFullscreen", "exitFullscreen", "fullscreenElement", "fullscreenEnabled", "fullscreenchange", "fullscreenerror"],
                    ["webkitRequestFullscreen", "webkitExitFullscreen", "webkitFullscreenElement", "webkitFullscreenEnabled", "webkitfullscreenchange", "webkitfullscreenerror"],
                    ["webkitRequestFullScreen", "webkitCancelFullScreen", "webkitCurrentFullScreenElement", "webkitCancelFullScreen", "webkitfullscreenchange", "webkitfullscreenerror"],
                    ["mozRequestFullScreen", "mozCancelFullScreen", "mozFullScreenElement", "mozFullScreenEnabled", "mozfullscreenchange", "mozfullscreenerror"],
                    ["msRequestFullscreen", "msExitFullscreen", "msFullscreenElement", "msFullscreenEnabled", "MSFullscreenChange", "MSFullscreenError"]
                ], d = 0, e = c.length, f = {}; e > d; d++)
                if (a = c[d], a && a[1] in document) { for (d = 0, b = a.length; b > d; d++) f[c[0][d]] = a[d]; return f }
            return !1 }(),
        d = { request: function(a) { var d = c.requestFullscreen;
                a = a || document.documentElement, /5\.1[\.\d]* Safari/.test(navigator.userAgent) ? a[d]() : a[d](b && Element.ALLOW_KEYBOARD_INPUT) }, exit: function() { document[c.exitFullscreen]() }, toggle: function(a) { this.isFullscreen ? this.exit() : this.request(a) }, onchange: function() {}, onerror: function() {}, raw: c }; return c ? (Object.defineProperties(d, { isFullscreen: { get: function() { return !!document[c.fullscreenElement] } }, element: { enumerable: !0, get: function() { return document[c.fullscreenElement] } }, enabled: { enumerable: !0, get: function() { return !!document[c.fullscreenEnabled] } } }), document.addEventListener(c.fullscreenchange, function(a) { d.onchange.call(d, a) }), document.addEventListener(c.fullscreenerror, function(a) { d.onerror.call(d, a) }), void(a ? module.exports = d : window.screenfull = d)) : void(a ? module.exports = !1 : window.screenfull = !1) }();
/*jQuery UI Widget 1.11.4*/
! function(a) { "function" == typeof define && define.amd ? define(["jquery"], a) : a(jQuery) }(function(a) { var b = 0,
        c = Array.prototype.slice; return a.cleanData = function(b) { return function(c) { var d, e, f; for (f = 0; null != (e = c[f]); f++) try { d = a._data(e, "events"), d && d.remove && a(e).triggerHandler("remove") } catch (g) {}
            b(c) } }(a.cleanData), a.widget = function(b, c, d) { var e, f, g, h, i = {},
            j = b.split(".")[0]; return b = b.split(".")[1], e = j + "-" + b, d || (d = c, c = a.Widget), a.expr[":"][e.toLowerCase()] = function(b) { return !!a.data(b, e) }, a[j] = a[j] || {}, f = a[j][b], g = a[j][b] = function(a, b) { return this._createWidget ? void(arguments.length && this._createWidget(a, b)) : new g(a, b) }, a.extend(g, f, { version: d.version, _proto: a.extend({}, d), _childConstructors: [] }), h = new c, h.options = a.widget.extend({}, h.options), a.each(d, function(b, d) { return a.isFunction(d) ? void(i[b] = function() { var a = function() { return c.prototype[b].apply(this, arguments) },
                    e = function(a) { return c.prototype[b].apply(this, a) }; return function() { var b, c = this._super,
                        f = this._superApply; return this._super = a, this._superApply = e, b = d.apply(this, arguments), this._super = c, this._superApply = f, b } }()) : void(i[b] = d) }), g.prototype = a.widget.extend(h, { widgetEventPrefix: f ? h.widgetEventPrefix || b : b }, i, { constructor: g, namespace: j, widgetName: b, widgetFullName: e }), f ? (a.each(f._childConstructors, function(b, c) { var d = c.prototype;
            a.widget(d.namespace + "." + d.widgetName, g, c._proto) }), delete f._childConstructors) : c._childConstructors.push(g), a.widget.bridge(b, g), g }, a.widget.extend = function(b) { for (var d, e, f = c.call(arguments, 1), g = 0, h = f.length; g < h; g++)
            for (d in f[g]) e = f[g][d], f[g].hasOwnProperty(d) && void 0 !== e && (a.isPlainObject(e) ? b[d] = a.isPlainObject(b[d]) ? a.widget.extend({}, b[d], e) : a.widget.extend({}, e) : b[d] = e); return b }, a.widget.bridge = function(b, d) { var e = d.prototype.widgetFullName || b;
        a.fn[b] = function(f) { var g = "string" == typeof f,
                h = c.call(arguments, 1),
                i = this; return g ? this.each(function() { var c, d = a.data(this, e); return "instance" === f ? (i = d, !1) : d ? a.isFunction(d[f]) && "_" !== f.charAt(0) ? (c = d[f].apply(d, h), c !== d && void 0 !== c ? (i = c && c.jquery ? i.pushStack(c.get()) : c, !1) : void 0) : a.error("no such method '" + f + "' for " + b + " widget instance") : a.error("cannot call methods on " + b + " prior to initialization; attempted to call method '" + f + "'") }) : (h.length && (f = a.widget.extend.apply(null, [f].concat(h))), this.each(function() { var b = a.data(this, e);
                b ? (b.option(f || {}), b._init && b._init()) : a.data(this, e, new d(f, this)) })), i } }, a.Widget = function() {}, a.Widget._childConstructors = [], a.Widget.prototype = { widgetName: "widget", widgetEventPrefix: "", defaultElement: "<div>", options: { disabled: !1, create: null }, _createWidget: function(c, d) { d = a(d || this.defaultElement || this)[0], this.element = a(d), this.uuid = b++, this.eventNamespace = "." + this.widgetName + this.uuid, this.bindings = a(), this.hoverable = a(), this.focusable = a(), d !== this && (a.data(d, this.widgetFullName, this), this._on(!0, this.element, { remove: function(a) { a.target === d && this.destroy() } }), this.document = a(d.style ? d.ownerDocument : d.document || d), this.window = a(this.document[0].defaultView || this.document[0].parentWindow)), this.options = a.widget.extend({}, this.options, this._getCreateOptions(), c), this._create(), this._trigger("create", null, this._getCreateEventData()), this._init() }, _getCreateOptions: a.noop, _getCreateEventData: a.noop, _create: a.noop, _init: a.noop, destroy: function() { this._destroy(), this.element.unbind(this.eventNamespace).removeData(this.widgetFullName).removeData(a.camelCase(this.widgetFullName)), this.widget().unbind(this.eventNamespace).removeAttr("aria-disabled").removeClass(this.widgetFullName + "-disabled ui-state-disabled"), this.bindings.unbind(this.eventNamespace), this.hoverable.removeClass("ui-state-hover"), this.focusable.removeClass("ui-state-focus") }, _destroy: a.noop, widget: function() { return this.element }, option: function(b, c) { var d, e, f, g = b; if (0 === arguments.length) return a.widget.extend({}, this.options); if ("string" == typeof b)
                if (g = {}, d = b.split("."), b = d.shift(), d.length) { for (e = g[b] = a.widget.extend({}, this.options[b]), f = 0; f < d.length - 1; f++) e[d[f]] = e[d[f]] || {}, e = e[d[f]]; if (b = d.pop(), 1 === arguments.length) return void 0 === e[b] ? null : e[b];
                    e[b] = c } else { if (1 === arguments.length) return void 0 === this.options[b] ? null : this.options[b];
                    g[b] = c }
            return this._setOptions(g), this }, _setOptions: function(a) { var b; for (b in a) this._setOption(b, a[b]); return this }, _setOption: function(a, b) { return this.options[a] = b, "disabled" === a && (this.widget().toggleClass(this.widgetFullName + "-disabled", !!b), b && (this.hoverable.removeClass("ui-state-hover"), this.focusable.removeClass("ui-state-focus"))), this }, enable: function() { return this._setOptions({ disabled: !1 }) }, disable: function() { return this._setOptions({ disabled: !0 }) }, _on: function(b, c, d) { var e, f = this; "boolean" != typeof b && (d = c, c = b, b = !1), d ? (c = e = a(c), this.bindings = this.bindings.add(c)) : (d = c, c = this.element, e = this.widget()), a.each(d, function(d, g) {
                function h() { if (b || f.options.disabled !== !0 && !a(this).hasClass("ui-state-disabled")) return ("string" == typeof g ? f[g] : g).apply(f, arguments) } "string" != typeof g && (h.guid = g.guid = g.guid || h.guid || a.guid++); var i = d.match(/^([\w:-]*)\s*(.*)$/),
                    j = i[1] + f.eventNamespace,
                    k = i[2];
                k ? e.delegate(k, j, h) : c.bind(j, h) }) }, _off: function(b, c) { c = (c || "").split(" ").join(this.eventNamespace + " ") + this.eventNamespace, b.unbind(c).undelegate(c), this.bindings = a(this.bindings.not(b).get()), this.focusable = a(this.focusable.not(b).get()), this.hoverable = a(this.hoverable.not(b).get()) }, _delay: function(a, b) {
            function c() { return ("string" == typeof a ? d[a] : a).apply(d, arguments) } var d = this; return setTimeout(c, b || 0) }, _hoverable: function(b) { this.hoverable = this.hoverable.add(b), this._on(b, { mouseenter: function(b) { a(b.currentTarget).addClass("ui-state-hover") }, mouseleave: function(b) { a(b.currentTarget).removeClass("ui-state-hover") } }) }, _focusable: function(b) { this.focusable = this.focusable.add(b), this._on(b, { focusin: function(b) { a(b.currentTarget).addClass("ui-state-focus") }, focusout: function(b) { a(b.currentTarget).removeClass("ui-state-focus") } }) }, _trigger: function(b, c, d) { var e, f, g = this.options[b]; if (d = d || {}, c = a.Event(c), c.type = (b === this.widgetEventPrefix ? b : this.widgetEventPrefix + b).toLowerCase(), c.target = this.element[0], f = c.originalEvent)
                for (e in f) e in c || (c[e] = f[e]); return this.element.trigger(c, d), !(a.isFunction(g) && g.apply(this.element[0], [c].concat(d)) === !1 || c.isDefaultPrevented()) } }, a.each({ show: "fadeIn", hide: "fadeOut" }, function(b, c) { a.Widget.prototype["_" + b] = function(d, e, f) { "string" == typeof e && (e = { effect: e }); var g, h = e ? e === !0 || "number" == typeof e ? c : e.effect || c : b;
            e = e || {}, "number" == typeof e && (e = { duration: e }), g = !a.isEmptyObject(e), e.complete = f, e.delay && d.delay(e.delay), g && a.effects && a.effects.effect[h] ? d[b](e) : h !== b && d[h] ? d[h](e.duration, e.easing, f) : d.queue(function(c) { a(this)[b](), f && f.call(d[0]), c() }) } }), a.widget });
/*jQuery UI Mouse 1.11.4*/
! function(a) { "function" == typeof define && define.amd ? define(["jquery", "./widget"], a) : a(jQuery) }(function(a) { var b = !1; return a(document).mouseup(function() { b = !1 }), a.widget("ui.mouse", { version: "1.11.4", options: { cancel: "input,textarea,button,select,option", distance: 1, delay: 0 }, _mouseInit: function() { var b = this;
            this.element.bind("mousedown." + this.widgetName, function(a) { return b._mouseDown(a) }).bind("click." + this.widgetName, function(c) { if (!0 === a.data(c.target, b.widgetName + ".preventClickEvent")) return a.removeData(c.target, b.widgetName + ".preventClickEvent"), c.stopImmediatePropagation(), !1 }), this.started = !1 }, _mouseDestroy: function() { this.element.unbind("." + this.widgetName), this._mouseMoveDelegate && this.document.unbind("mousemove." + this.widgetName, this._mouseMoveDelegate).unbind("mouseup." + this.widgetName, this._mouseUpDelegate) }, _mouseDown: function(c) { if (!b) { this._mouseMoved = !1, this._mouseStarted && this._mouseUp(c), this._mouseDownEvent = c; var d = this,
                    e = 1 === c.which,
                    f = !("string" != typeof this.options.cancel || !c.target.nodeName) && a(c.target).closest(this.options.cancel).length; return !(e && !f && this._mouseCapture(c)) || (this.mouseDelayMet = !this.options.delay, this.mouseDelayMet || (this._mouseDelayTimer = setTimeout(function() { d.mouseDelayMet = !0 }, this.options.delay)), this._mouseDistanceMet(c) && this._mouseDelayMet(c) && (this._mouseStarted = this._mouseStart(c) !== !1, !this._mouseStarted) ? (c.preventDefault(), !0) : (!0 === a.data(c.target, this.widgetName + ".preventClickEvent") && a.removeData(c.target, this.widgetName + ".preventClickEvent"), this._mouseMoveDelegate = function(a) { return d._mouseMove(a) }, this._mouseUpDelegate = function(a) { return d._mouseUp(a) }, this.document.bind("mousemove." + this.widgetName, this._mouseMoveDelegate).bind("mouseup." + this.widgetName, this._mouseUpDelegate), c.preventDefault(), b = !0, !0)) } }, _mouseMove: function(b) { if (this._mouseMoved) { if (a.ui.ie && (!document.documentMode || document.documentMode < 9) && !b.button) return this._mouseUp(b); if (!b.which) return this._mouseUp(b) } return (b.which || b.button) && (this._mouseMoved = !0), this._mouseStarted ? (this._mouseDrag(b), b.preventDefault()) : (this._mouseDistanceMet(b) && this._mouseDelayMet(b) && (this._mouseStarted = this._mouseStart(this._mouseDownEvent, b) !== !1, this._mouseStarted ? this._mouseDrag(b) : this._mouseUp(b)), !this._mouseStarted) }, _mouseUp: function(c) { return this.document.unbind("mousemove." + this.widgetName, this._mouseMoveDelegate).unbind("mouseup." + this.widgetName, this._mouseUpDelegate), this._mouseStarted && (this._mouseStarted = !1, c.target === this._mouseDownEvent.target && a.data(c.target, this.widgetName + ".preventClickEvent", !0), this._mouseStop(c)), b = !1, !1 }, _mouseDistanceMet: function(a) { return Math.max(Math.abs(this._mouseDownEvent.pageX - a.pageX), Math.abs(this._mouseDownEvent.pageY - a.pageY)) >= this.options.distance }, _mouseDelayMet: function() { return this.mouseDelayMet }, _mouseStart: function() {}, _mouseDrag: function() {}, _mouseStop: function() {}, _mouseCapture: function() { return !0 } }) });
/*jQuery UI Slider 1.11.4*/
! function(a) { "function" == typeof define && define.amd ? define(["jquery", "./core", "./mouse", "./widget"], a) : a(jQuery) }(function(a) { return a.widget("ui.slider", a.ui.mouse, { version: "1.11.4", widgetEventPrefix: "slide", options: { animate: !1, distance: 0, max: 100, min: 0, orientation: "horizontal", range: !1, step: 1, value: 0, values: null, change: null, slide: null, start: null, stop: null }, numPages: 5, _create: function() { this._keySliding = !1, this._mouseSliding = !1, this._animateOff = !0, this._handleIndex = null, this._detectOrientation(), this._mouseInit(), this._calculateNewMax(), this.element.addClass("ui-slider ui-slider-" + this.orientation + " ui-widget ui-widget-content ui-corner-all"), this._refresh(), this._setOption("disabled", this.options.disabled), this._animateOff = !1 }, _refresh: function() { this._createRange(), this._createHandles(), this._setupEvents(), this._refreshValue() }, _createHandles: function() { var b, c, d = this.options,
                e = this.element.find(".ui-slider-handle").addClass("ui-state-default ui-corner-all"),
                f = "<span class='ui-slider-handle ui-state-default ui-corner-all' tabindex='0'></span>",
                g = []; for (c = d.values && d.values.length || 1, e.length > c && (e.slice(c).remove(), e = e.slice(0, c)), b = e.length; b < c; b++) g.push(f);
            this.handles = e.add(a(g.join("")).appendTo(this.element)), this.handle = this.handles.eq(0), this.handles.each(function(b) { a(this).data("ui-slider-handle-index", b) }) }, _createRange: function() { var b = this.options,
                c = "";
            b.range ? (b.range === !0 && (b.values ? b.values.length && 2 !== b.values.length ? b.values = [b.values[0], b.values[0]] : a.isArray(b.values) && (b.values = b.values.slice(0)) : b.values = [this._valueMin(), this._valueMin()]), this.range && this.range.length ? this.range.removeClass("ui-slider-range-min ui-slider-range-max").css({ left: "", bottom: "" }) : (this.range = a("<div></div>").appendTo(this.element), c = "ui-slider-range ui-widget-header ui-corner-all"), this.range.addClass(c + ("min" === b.range || "max" === b.range ? " ui-slider-range-" + b.range : ""))) : (this.range && this.range.remove(), this.range = null) }, _setupEvents: function() { this._off(this.handles), this._on(this.handles, this._handleEvents), this._hoverable(this.handles), this._focusable(this.handles) }, _destroy: function() { this.handles.remove(), this.range && this.range.remove(), this.element.removeClass("ui-slider ui-slider-horizontal ui-slider-vertical ui-widget ui-widget-content ui-corner-all"), this._mouseDestroy() }, _mouseCapture: function(b) { var c, d, e, f, g, h, i, j, k = this,
                l = this.options; return !l.disabled && (this.elementSize = { width: this.element.outerWidth(), height: this.element.outerHeight() }, this.elementOffset = this.element.offset(), c = { x: b.pageX, y: b.pageY }, d = this._normValueFromMouse(c), e = this._valueMax() - this._valueMin() + 1, this.handles.each(function(b) { var c = Math.abs(d - k.values(b));
                (e > c || e === c && (b === k._lastChangedValue || k.values(b) === l.min)) && (e = c, f = a(this), g = b) }), h = this._start(b, g), h !== !1 && (this._mouseSliding = !0, this._handleIndex = g, f.addClass("ui-state-active").focus(), i = f.offset(), j = !a(b.target).parents().addBack().is(".ui-slider-handle"), this._clickOffset = j ? { left: 0, top: 0 } : { left: b.pageX - i.left - f.width() / 2, top: b.pageY - i.top - f.height() / 2 - (parseInt(f.css("borderTopWidth"), 10) || 0) - (parseInt(f.css("borderBottomWidth"), 10) || 0) + (parseInt(f.css("marginTop"), 10) || 0) }, this.handles.hasClass("ui-state-hover") || this._slide(b, g, d), this._animateOff = !0, !0)) }, _mouseStart: function() { return !0 }, _mouseDrag: function(a) { var b = { x: a.pageX, y: a.pageY },
                c = this._normValueFromMouse(b); return this._slide(a, this._handleIndex, c), !1 }, _mouseStop: function(a) { return this.handles.removeClass("ui-state-active"), this._mouseSliding = !1, this._stop(a, this._handleIndex), this._change(a, this._handleIndex), this._handleIndex = null, this._clickOffset = null, this._animateOff = !1, !1 }, _detectOrientation: function() { this.orientation = "vertical" === this.options.orientation ? "vertical" : "horizontal" }, _normValueFromMouse: function(a) { var b, c, d, e, f; return "horizontal" === this.orientation ? (b = this.elementSize.width, c = a.x - this.elementOffset.left - (this._clickOffset ? this._clickOffset.left : 0)) : (b = this.elementSize.height, c = a.y - this.elementOffset.top - (this._clickOffset ? this._clickOffset.top : 0)), d = c / b, d > 1 && (d = 1), d < 0 && (d = 0), "vertical" === this.orientation && (d = 1 - d), e = this._valueMax() - this._valueMin(), f = this._valueMin() + d * e, this._trimAlignValue(f) }, _start: function(a, b) { var c = { handle: this.handles[b], value: this.value() }; return this.options.values && this.options.values.length && (c.value = this.values(b), c.values = this.values()), this._trigger("start", a, c) }, _slide: function(a, b, c) { var d, e, f;
            this.options.values && this.options.values.length ? (d = this.values(b ? 0 : 1), 2 === this.options.values.length && this.options.range === !0 && (0 === b && c > d || 1 === b && c < d) && (c = d), c !== this.values(b) && (e = this.values(), e[b] = c, f = this._trigger("slide", a, { handle: this.handles[b], value: c, values: e }), d = this.values(b ? 0 : 1), f !== !1 && this.values(b, c))) : c !== this.value() && (f = this._trigger("slide", a, { handle: this.handles[b], value: c }), f !== !1 && this.value(c)) }, _stop: function(a, b) { var c = { handle: this.handles[b], value: this.value() };
            this.options.values && this.options.values.length && (c.value = this.values(b), c.values = this.values()), this._trigger("stop", a, c) }, _change: function(a, b) { if (!this._keySliding && !this._mouseSliding) { var c = { handle: this.handles[b], value: this.value() };
                this.options.values && this.options.values.length && (c.value = this.values(b), c.values = this.values()), this._lastChangedValue = b, this._trigger("change", a, c) } }, value: function(a) { return arguments.length ? (this.options.value = this._trimAlignValue(a), this._refreshValue(), void this._change(null, 0)) : this._value() }, values: function(b, c) { var d, e, f; if (arguments.length > 1) return this.options.values[b] = this._trimAlignValue(c), this._refreshValue(), void this._change(null, b); if (!arguments.length) return this._values(); if (!a.isArray(arguments[0])) return this.options.values && this.options.values.length ? this._values(b) : this.value(); for (d = this.options.values, e = arguments[0], f = 0; f < d.length; f += 1) d[f] = this._trimAlignValue(e[f]), this._change(null, f);
            this._refreshValue() }, _setOption: function(b, c) { var d, e = 0; switch ("range" === b && this.options.range === !0 && ("min" === c ? (this.options.value = this._values(0), this.options.values = null) : "max" === c && (this.options.value = this._values(this.options.values.length - 1), this.options.values = null)), a.isArray(this.options.values) && (e = this.options.values.length), "disabled" === b && this.element.toggleClass("ui-state-disabled", !!c), this._super(b, c), b) {
                case "orientation":
                    this._detectOrientation(), this.element.removeClass("ui-slider-horizontal ui-slider-vertical").addClass("ui-slider-" + this.orientation), this._refreshValue(), this.handles.css("horizontal" === c ? "bottom" : "left", ""); break;
                case "value":
                    this._animateOff = !0, this._refreshValue(), this._change(null, 0), this._animateOff = !1; break;
                case "values":
                    for (this._animateOff = !0, this._refreshValue(), d = 0; d < e; d += 1) this._change(null, d);
                    this._animateOff = !1; break;
                case "step":
                case "min":
                case "max":
                    this._animateOff = !0, this._calculateNewMax(), this._refreshValue(), this._animateOff = !1; break;
                case "range":
                    this._animateOff = !0, this._refresh(), this._animateOff = !1 } }, _value: function() { var a = this.options.value; return a = this._trimAlignValue(a) }, _values: function(a) { var b, c, d; if (arguments.length) return b = this.options.values[a], b = this._trimAlignValue(b); if (this.options.values && this.options.values.length) { for (c = this.options.values.slice(), d = 0; d < c.length; d += 1) c[d] = this._trimAlignValue(c[d]); return c } return [] }, _trimAlignValue: function(a) { if (a <= this._valueMin()) return this._valueMin(); if (a >= this._valueMax()) return this._valueMax(); var b = this.options.step > 0 ? this.options.step : 1,
                c = (a - this._valueMin()) % b,
                d = a - c; return 2 * Math.abs(c) >= b && (d += c > 0 ? b : -b), parseFloat(d.toFixed(5)) }, _calculateNewMax: function() { var a = this.options.max,
                b = this._valueMin(),
                c = this.options.step,
                d = Math.floor(+(a - b).toFixed(this._precision()) / c) * c;
            a = d + b, this.max = parseFloat(a.toFixed(this._precision())) }, _precision: function() { var a = this._precisionOf(this.options.step); return null !== this.options.min && (a = Math.max(a, this._precisionOf(this.options.min))), a }, _precisionOf: function(a) { var b = a.toString(),
                c = b.indexOf("."); return c === -1 ? 0 : b.length - c - 1 }, _valueMin: function() { return this.options.min }, _valueMax: function() { return this.max }, _refreshValue: function() { var b, c, d, e, f, g = this.options.range,
                h = this.options,
                i = this,
                j = !this._animateOff && h.animate,
                k = {};
            this.options.values && this.options.values.length ? this.handles.each(function(d) { c = (i.values(d) - i._valueMin()) / (i._valueMax() - i._valueMin()) * 100, k["horizontal" === i.orientation ? "left" : "bottom"] = c + "%", a(this).stop(1, 1)[j ? "animate" : "css"](k, h.animate), i.options.range === !0 && ("horizontal" === i.orientation ? (0 === d && i.range.stop(1, 1)[j ? "animate" : "css"]({ left: c + "%" }, h.animate), 1 === d && i.range[j ? "animate" : "css"]({ width: c - b + "%" }, { queue: !1, duration: h.animate })) : (0 === d && i.range.stop(1, 1)[j ? "animate" : "css"]({ bottom: c + "%" }, h.animate), 1 === d && i.range[j ? "animate" : "css"]({ height: c - b + "%" }, { queue: !1, duration: h.animate }))), b = c }) : (d = this.value(), e = this._valueMin(), f = this._valueMax(), c = f !== e ? (d - e) / (f - e) * 100 : 0, k["horizontal" === this.orientation ? "left" : "bottom"] = c + "%", this.handle.stop(1, 1)[j ? "animate" : "css"](k, h.animate), "min" === g && "horizontal" === this.orientation && this.range.stop(1, 1)[j ? "animate" : "css"]({ width: c + "%" }, h.animate), "max" === g && "horizontal" === this.orientation && this.range[j ? "animate" : "css"]({ width: 100 - c + "%" }, { queue: !1, duration: h.animate }), "min" === g && "vertical" === this.orientation && this.range.stop(1, 1)[j ? "animate" : "css"]({ height: c + "%" }, h.animate), "max" === g && "vertical" === this.orientation && this.range[j ? "animate" : "css"]({ height: 100 - c + "%" }, { queue: !1, duration: h.animate })) }, _handleEvents: { keydown: function(b) { var c, d, e, f, g = a(b.target).data("ui-slider-handle-index"); switch (b.keyCode) {
                    case a.ui.keyCode.HOME:
                    case a.ui.keyCode.END:
                    case a.ui.keyCode.PAGE_UP:
                    case a.ui.keyCode.PAGE_DOWN:
                    case a.ui.keyCode.UP:
                    case a.ui.keyCode.RIGHT:
                    case a.ui.keyCode.DOWN:
                    case a.ui.keyCode.LEFT:
                        if (b.preventDefault(), !this._keySliding && (this._keySliding = !0, a(b.target).addClass("ui-state-active"), c = this._start(b, g), c === !1)) return } switch (f = this.options.step, d = e = this.options.values && this.options.values.length ? this.values(g) : this.value(), b.keyCode) {
                    case a.ui.keyCode.HOME:
                        e = this._valueMin(); break;
                    case a.ui.keyCode.END:
                        e = this._valueMax(); break;
                    case a.ui.keyCode.PAGE_UP:
                        e = this._trimAlignValue(d + (this._valueMax() - this._valueMin()) / this.numPages); break;
                    case a.ui.keyCode.PAGE_DOWN:
                        e = this._trimAlignValue(d - (this._valueMax() - this._valueMin()) / this.numPages); break;
                    case a.ui.keyCode.UP:
                    case a.ui.keyCode.RIGHT:
                        if (d === this._valueMax()) return;
                        e = this._trimAlignValue(d + f); break;
                    case a.ui.keyCode.DOWN:
                    case a.ui.keyCode.LEFT:
                        if (d === this._valueMin()) return;
                        e = this._trimAlignValue(d - f) }
                this._slide(b, g, e) }, keyup: function(b) { var c = a(b.target).data("ui-slider-handle-index");
                this._keySliding && (this._keySliding = !1, this._stop(b, c), this._change(b, c), a(b.target).removeClass("ui-state-active")) } } }) });
/*jQuery UI Progressbar 1.11.4*/
! function(a) { "function" == typeof define && define.amd ? define(["jquery", "./core", "./widget"], a) : a(jQuery) }(function(a) { return a.widget("ui.progressbar", { version: "1.11.4", options: { max: 100, value: 0, change: null, complete: null }, min: 0, _create: function() { this.oldValue = this.options.value = this._constrainedValue(), this.element.addClass("ui-progressbar ui-widget ui-widget-content ui-corner-all").attr({ role: "progressbar", "aria-valuemin": this.min }), this.valueDiv = a("<div class='ui-progressbar-value ui-widget-header ui-corner-left'></div>").appendTo(this.element), this._refreshValue() }, _destroy: function() { this.element.removeClass("ui-progressbar ui-widget ui-widget-content ui-corner-all").removeAttr("role").removeAttr("aria-valuemin").removeAttr("aria-valuemax").removeAttr("aria-valuenow"), this.valueDiv.remove() }, value: function(a) { return void 0 === a ? this.options.value : (this.options.value = this._constrainedValue(a), void this._refreshValue()) }, _constrainedValue: function(a) { return void 0 === a && (a = this.options.value), this.indeterminate = a === !1, "number" != typeof a && (a = 0), !this.indeterminate && Math.min(this.options.max, Math.max(this.min, a)) }, _setOptions: function(a) { var b = a.value;
            delete a.value, this._super(a), this.options.value = this._constrainedValue(b), this._refreshValue() }, _setOption: function(a, b) { "max" === a && (b = Math.max(this.min, b)), "disabled" === a && this.element.toggleClass("ui-state-disabled", !!b).attr("aria-disabled", b), this._super(a, b) }, _percentage: function() { return this.indeterminate ? 100 : 100 * (this.options.value - this.min) / (this.options.max - this.min) }, _refreshValue: function() { var b = this.options.value,
                c = this._percentage();
            this.valueDiv.toggle(this.indeterminate || b > this.min).toggleClass("ui-corner-right", b === this.options.max).width(c.toFixed(0) + "%"), this.element.toggleClass("ui-progressbar-indeterminate", this.indeterminate), this.indeterminate ? (this.element.removeAttr("aria-valuenow"), this.overlayDiv || (this.overlayDiv = a("<div class='ui-progressbar-overlay'></div>").appendTo(this.valueDiv))) : (this.element.attr({ "aria-valuemax": this.options.max, "aria-valuenow": b }), this.overlayDiv && (this.overlayDiv.remove(), this.overlayDiv = null)), this.oldValue !== b && (this.oldValue = b, this._trigger("change")), b === this.options.max && this._trigger("complete") } }) });